data<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
data$Time <- strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date,"%d/%m/%Y")
sample<-subset(data,Date=="2007/02/01" | Date=="2007/02/02")
#Plot 3
plot(sample$Time,sample$Global_active_power,xlab="",ylab="Energy sub metering",type="n", xaxt="n")
points(sample$Time,sample$Sub_metering_1,type="l",col="black")
points(sample$Time,sample$Sub_metering_2,type="l",col="red")
points(sample$Time,sample$Sub_metering_3,type="l",col="blue")
dayrange <- round(range(sample$Time), "days")
axis.POSIXct(1, at = seq(dayrange[1], dayrange[2], by = "day"), format = "%a")
legend("topright",pch="-",  col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.copy(png, file="plot3.png", width=480, height=480, units="px")
dev.off()