data<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
data$Time <- strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date,"%d/%m/%Y")
sample<-subset(data,Date=="2007/02/01" | Date=="2007/02/02")
#Plot 2
plot(sample$Time,sample$Global_active_power,xlab="",ylab="Global Active Power (kilowatts)",type="l", xaxt="n")
dayrange <- round(range(sample$Time), "days")
axis.POSIXct(1, at = seq(dayrange[1], dayrange[2], by = "day"), format = "%a")
dev.copy(png, file="plot2.png", width=480, height=480, units="px")
dev.off()